// Code generated by MockGen. DO NOT EDIT.
// Source: src/Applications/generator/generator.go
//
// Generated by this command:
//
//	mockgen -source=src/Applications/generator/generator.go -destination=src/mocks/generator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGeneratorId is a mock of GeneratorId interface.
type MockGeneratorId struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorIdMockRecorder
	isgomock struct{}
}

// MockGeneratorIdMockRecorder is the mock recorder for MockGeneratorId.
type MockGeneratorIdMockRecorder struct {
	mock *MockGeneratorId
}

// NewMockGeneratorId creates a new mock instance.
func NewMockGeneratorId(ctrl *gomock.Controller) *MockGeneratorId {
	mock := &MockGeneratorId{ctrl: ctrl}
	mock.recorder = &MockGeneratorIdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeneratorId) EXPECT() *MockGeneratorIdMockRecorder {
	return m.recorder
}

// Generator mocks base method.
func (m *MockGeneratorId) Generator() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generator")
	ret0, _ := ret[0].(string)
	return ret0
}

// Generator indicates an expected call of Generator.
func (mr *MockGeneratorIdMockRecorder) Generator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generator", reflect.TypeOf((*MockGeneratorId)(nil).Generator))
}
