// Code generated by MockGen. DO NOT EDIT.
// Source: src/Domains/subscription_repository.go
//
// Generated by this command:
//
//	mockgen -source=src/Domains/subscription_repository.go -destination=src/mocks/subscription_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	entities "subscription-service/src/Domains/entities"

	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// CreateSubscriptions mocks base method.
func (m *MockSubscriptionRepository) CreateSubscriptions(subs *entities.Subscriptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscriptions", subs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubscriptions indicates an expected call of CreateSubscriptions.
func (mr *MockSubscriptionRepositoryMockRecorder) CreateSubscriptions(subs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscriptions", reflect.TypeOf((*MockSubscriptionRepository)(nil).CreateSubscriptions), subs)
}

// FindSubscriptionByName mocks base method.
func (m *MockSubscriptionRepository) FindSubscriptionByName(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSubscriptionByName", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindSubscriptionByName indicates an expected call of FindSubscriptionByName.
func (mr *MockSubscriptionRepositoryMockRecorder) FindSubscriptionByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSubscriptionByName", reflect.TypeOf((*MockSubscriptionRepository)(nil).FindSubscriptionByName), name)
}
