// Code generated by MockGen. DO NOT EDIT.
// Source: src/Domains/user_subscription_repository.go
//
// Generated by this command:
//
//	mockgen -source=src/Domains/user_subscription_repository.go -destination=src/mocks/user_subscription_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	entities "subscription-service/src/Domains/entities"

	gomock "go.uber.org/mock/gomock"
)

// MockUserSubscriptionRepository is a mock of UserSubscriptionRepository interface.
type MockUserSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockUserSubscriptionRepositoryMockRecorder is the mock recorder for MockUserSubscriptionRepository.
type MockUserSubscriptionRepositoryMockRecorder struct {
	mock *MockUserSubscriptionRepository
}

// NewMockUserSubscriptionRepository creates a new mock instance.
func NewMockUserSubscriptionRepository(ctrl *gomock.Controller) *MockUserSubscriptionRepository {
	mock := &MockUserSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockUserSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSubscriptionRepository) EXPECT() *MockUserSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// CreateUserSubscription mocks base method.
func (m *MockUserSubscriptionRepository) CreateUserSubscription(userSub *entities.UserSubscriptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserSubscription", userSub)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserSubscription indicates an expected call of CreateUserSubscription.
func (mr *MockUserSubscriptionRepositoryMockRecorder) CreateUserSubscription(userSub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserSubscription", reflect.TypeOf((*MockUserSubscriptionRepository)(nil).CreateUserSubscription), userSub)
}
